lexik_jwt_authentication:
  secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  pass_phrase: '%env(JWT_PASSPHRASE)%'
  token_ttl: 900 # 15min
  user_identity_field: email

  token_extractors:
    cookie:
      enabled: true

  set_cookies:
    BEARER: ~
