security:
  enable_authenticator_manager: true
  
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  password_hashers:
    App\Entity\User:
      algorithm: auto
  
  firewalls:
    api_token_refresh:
      pattern: ^/token/refresh
      stateless: true
      refresh_jwt:
        provider: app_user_provider
    
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
      
    login:
      pattern: ^/login
      stateless: true
      json_login:
        check_path: /login_check
        provider: app_user_provider
        username_path: email
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/
      stateless: true
      provider: app_user_provider
      jwt: ~

  access_control:
    - { path: ^/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
